import re
from typing import Dict, Any, List, Optional
from app.rag.retriever import retriever
from app.agent.prompts import ARTIFACT_GENERATOR_SYSTEM_PROMPT
from app.llm.base import BaseLLM

class ArtifactSkill:
    def __init__(self):
        pass

    def execute(
        self,
        query: str,
        llm: BaseLLM,
        conversation_history: Optional[List[Dict[str, str]]] = None
    ) -> Dict[str, Any]:
        # Search relevant transcripts for framework data
        cleaned_search = re.sub(
            r'(?i)\b(create|generate|build|make|design|an?|interactive|html|css|framework|checklist|artifact|matrix|template|scorecard|with)\b',
            '',
            query
        ).strip()
        cleaned_search = re.sub(r'^[^\w]+|[^\w]+$', '', cleaned_search).strip()

        if not cleaned_search and conversation_history:
            for m in reversed(conversation_history):
                if m["role"] == "user":
                    cleaned_search = re.sub(
                        r'(?i)\b(create|generate|build|make|design|an?|interactive|html|css|framework|checklist|artifact|matrix|template|scorecard|with)\b',
                        '',
                        m["content"]
                    ).strip()
                    break

        if not cleaned_search:
            cleaned_search = "product retention and growth framework"

        search_res = retriever.search(cleaned_search, top_k=4, threshold=0.05)
        context_str = retriever.format_sources_for_prompt(search_res["results"])

        prompt = (
            f"Retrieved Transcript Passages from Lenny's Podcast:\n"
            f"{context_str}\n\n"
            f"Topic / Prompt: {query}\n\n"
            f"User Request: {query}\n\n"
            f"Assignment: Generate a beautiful, responsive HTML/CSS framework or checklist artifact based strictly on the above knowledge for: {query}"
        )

        response_text = llm.generate(
            prompt=prompt,
            system_prompt=ARTIFACT_GENERATOR_SYSTEM_PROMPT,
            temperature=0.6,
            max_tokens=2500
        )

        # Extract HTML code block if wrapped in markdown
        html_match = re.search(r'```(?:html)?\s*(<!DOCTYPE html[\s\S]*?</html>)\s*```', response_text, re.IGNORECASE)
        if not html_match:
            html_match = re.search(r'```(?:html)?\s*(<[\s\S]*?>[\s\S]*?)\s*```', response_text, re.IGNORECASE)

        if html_match:
            raw_html = html_match.group(1).strip()
        else:
            raw_html = response_text.strip()

        # Sanitize HTML: Disallow dangerous elements (script tags, iframe, object, embed, javascript: URI)
        sanitized_html = self._sanitize_html(raw_html)

        # Extract title
        title_match = re.search(r'<title>(.*?)</title>', raw_html, re.IGNORECASE)
        if not title_match:
            title_match = re.search(r'<h1>(.*?)</h1>', raw_html, re.IGNORECASE)

        title = title_match.group(1).strip() if title_match else "Lenny Growth Framework"
        # Strip internal tags from title if any
        title = re.sub(r'<[^>]+>', '', title)

        chat_message = (
            f"I have created the **{title}** artifact based on Lenny's Podcast insights. "
            f"You can view and interact with it in the **Artifact Viewer** to the right!"
        )

        return {
            "content": chat_message,
            "artifact": {
                "title": title,
                "type": "html",
                "content": sanitized_html
            },
            "sources": search_res["results"],
            "is_grounded": True,
            "skill": "artifact"
        }

    def _sanitize_html(self, html: str) -> str:
        """
        Sanitizes untrusted HTML generated by the model.
        Strips script tags, event handlers (onload, onclick), and iframe tags.
        """
        # Remove script tags and content
        cleaned = re.sub(r'<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>', '', html, flags=re.IGNORECASE)
        # Remove event handlers (e.g. onclick="...", onerror="...")
        cleaned = re.sub(r'\son\w+\s*=\s*["\'][^"\']*["\']', '', cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r'\son\w+\s*=\s*[^\s>]+', '', cleaned, flags=re.IGNORECASE)
        # Remove javascript: pseudo-protocol
        cleaned = re.sub(r'href\s*=\s*["\']javascript:[^"\']*["\']', 'href="#"', cleaned, flags=re.IGNORECASE)
        # Remove iframe, object, embed tags
        cleaned = re.sub(r'<\/?(?:iframe|object|embed|base)\b[^>]*>', '', cleaned, flags=re.IGNORECASE)
        return cleaned
